/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

import { clientsClaim } from "workbox-core";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { NetworkFirst, NetworkOnly } from "workbox-strategies";
import { BackgroundSyncPlugin } from "workbox-background-sync";

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

const bgSyncPlugin = new BackgroundSyncPlugin("addUserQueue", {
  maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
  onSync: async ({ queue }) => {
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        console.log("Attempting to replay request", entry.request);
        await fetch(entry.request);
        console.log("Replay succeeded for request", entry.request);

        // Notify all clients that sync is complete
        self.clients.matchAll({ type: "window" }).then((clients) => {
          clients.forEach((client) => {
            client.postMessage({ type: "SYNC_COMPLETE" });
          });
        });
      } catch (error) {
        console.error("Replay failed for request", entry.request, error);
        await queue.unshiftRequest(entry);
        throw error;
      }
    }
  },
});

// App Shell-style routing, fulfilled with index.html.
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(({ request, url }: { request: Request; url: URL }) => {
  if (request.mode !== "navigate") {
    return false;
  }
  if (url.pathname.startsWith("/_")) {
    return false;
  }
  if (url.pathname.match(fileExtensionRegexp)) {
    return false;
  }
  return true;
}, createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html"));

// Network-first strategy for HTML files.
registerRoute(
  ({ request }) => request.destination === "document",
  new NetworkFirst({
    cacheName: "documents-cache",
  })
);

// Network-first strategy for CSS and JS files.
registerRoute(
  ({ request }) =>
    request.destination === "style" || request.destination === "script",
  new NetworkFirst({
    cacheName: "static-resources-cache",
  })
);

// Network-first strategy for images.
registerRoute(
  ({ request }) => request.destination === "image",
  new NetworkFirst({
    cacheName: "images-cache",
  })
);

// Register background sync for POST requests to /users
registerRoute(
  ({ url, request }) => {
    console.log("1", url, "2", request);
    return (
      url.href === "http://localhost:3001/users" && request.method === "POST"
    );
  },
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  "POST"
);

// Skip waiting for the new service worker to activate immediately.
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Log messages to debug sync events
self.addEventListener("sync", (event) => {
  console.log("Sync event triggered:", event);
  if (event.tag === "addUserQueue") {
    console.log("Sync event: addUserQueue");
  }
});
